- hosts: localhost
  gather_facts: yes
  become: false
  vars:
    a: "{{ansible_distribution}}"
    b: "{{ansible_distribution_version}}"
  tasks:
  - name: System details
    debug: msg="{{item}}"
    with_items: 
    - "{{ansible_distribution}}"
    - "{{ansible_distribution_version}}"
  - name: Set authorized keys taken from url
    authorized_key:
      user: root
      state: present
      key: https://github.com/mb243.keys

  - include_tasks: "distros/{{a}}.{{b}}.yml"
