- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_major_version }}"
    - "{{ ansible_distribution_version }}"
  - import_tasks: centos.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - import_tasks: debian.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
